### ISSUE TITLE
Why each query just can collect 1000 elements

### ISSUE THREAD

**Issue by DerZc** [rsain/GitHub-Crawler#1]
Different subqueries if you need to collect more than 1000 elements.
When I run in page 11, it stop

**Comment by rsain** [comment]
At the time of publishing this code, GitHub limited to 1,000 elements per query. For this reason I proposed to split the main query in subqueries.

I am not sure what your issue is. If you mean that the script fails after processing 10 pages, most probably this is due to the fact that your query returned more than 1,000 elements. If it is the case, you must define subqueries as commented in the code using the constant SUBQUERIES. As example, let suppose that your initial query returns 1,900 elements. In this case, you could split the initial query in two different subqueries (each of them returning less than 1,000 elements).

I hope it helps.

**Comment by DerZc** [comment]
I get it, thank you very much. It is the same reason.
